### ISSUE TITLE
Rocky Linux support

### ISSUE THREAD

**Issue by FlyinPancake** [juju4/ansible-MISP#11]
Hi I'd like this role to support rocky linux.
It's a drop in replacement for CentOS afaik so I was hoping it wouldn't be much work.

Thanks in advance :smile:

**Comment by juju4** [comment]
vars includes RedHat-8, RedHat as the family which likely includes rockylinux too
https://github.com/juju4/ansible-MISP/blob/master/tasks/main.yml#L6
https://github.com/juju4/ansible-MISP/tree/master/vars
and github actions includes centos-8 stream, even if failing on API call currently.

My typical setup is more on ubuntu side. Role could benefit from additional reviews.
Feel free to share issues you found

**Comment by juju4** [comment]
Closing as no more updates
