### ISSUE TITLE
Ansible Installation on Ubuntu 22.04 error installing pip requirements

### ISSUE THREAD

**Issue by letmeadministratethisforyou** [juju4/ansible-MISP#27]
### Prerequisites

- [X] Ensure no duplicate issue
- [X] Using an up-to-date latest release or tag
- [X] Tested an up-to-date latest HEAD
- [X] Collected play logs on verbose mode aka `ansible-playbook -vvv playbook.yml`. Redact any sensitive information.
- [X] Ensuring using latest stable underlying software (ansible, operating systems...)

### Your Environment

* Version used: Python 3.10.12
* Server type and version: Virtual Machine on VMWare ESXi
* Operating System and version: Ubuntu 22.04 server

### Expected behavior

Ansible Skript will install misp by executing the provided role.

### Actual behavior

I included the Role in an extra Playbook:
```
---
- name: install ansible-misp role
  hosts: all
  gather_facts: yes
  remote_user: "{{ remoteuser }}"
  become: True
  become_user: root
  roles:
    - ansible-MISP
```
remoteuser is a working ssh user with sudo privileges.

If i run the role i get the output shown in 240328_misp_ansible_ubuntu2204_error.

If i run the role with -vvv i get the output shown in 240328_misp_ansible_ubuntu2204_error-vvv.

If i try to run the Command directly i get the errors shown in 240328_misp_ansible_ubuntu2204_error_manueller_fehler.

### Steps to reproduce

- Set up a new Ubuntu 22.04 server
- run the ansible role

### More context

I am not able to get misp on Ubuntu 22.04 server running. There seems to be an issue installing the pip requirements. I tried installing them by hand but kept running in errors.

### Relevant log output

See attached Files

### Extra attachments

[240328_misp_ansible_ubuntu2204_error_manueller_fehler.txt](https://github.com/juju4/ansible-MISP/files/14788614/240328_misp_ansible_ubuntu2204_error_manueller_fehler.txt)
[240328_misp_ansible_ubuntu2204_error-vvv.txt](https://github.com/juju4/ansible-MISP/files/14788616/240328_misp_ansible_ubuntu2204_error-vvv.txt)
[240328_misp_ansible_ubuntu2204_error.txt](https://github.com/juju4/ansible-MISP/files/14788617/240328_misp_ansible_ubuntu2204_error.txt)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by juju4** [comment]
Thanks for reporting.
Sadly, I won't be able to review/fix anytime soon. Please submit a PR if find a fix.

From a very quick look, it seems related to numpy. possibly a python version support issue.
From https://numpy.org/news/, supported python is 3.9-3.12 so maybe a dependency...
no match in https://github.com/search?q=repo%3AMISP%2FMISP+numpy&type=issues

**Comment by juju4** [comment]
Any update here?
I did review a bit role yesterday and currently, for github actions, it completes successfully on 22.04 (and only. need to check current supported distrib+php).

**Comment by juju4** [comment]
Closing old issue and no feedback.
