### ISSUE TITLE
Feature request: Missing support to Ubuntu 24.04 (noble)

### ISSUE THREAD

**Issue by leowinterde** [juju4/ansible-MISP#28]
### Detailed Description

Hello, is there any support for Ubuntu 24.04 (noble) planned?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by juju4** [comment]
Likely but not high on my current priority list. Need to review changes in https://github.com/MISP/MISP/blob/2.5/INSTALL/INSTALL.ubuntu2404.sh and basically "port" https://github.com/juju4/ansible-MISP/blob/main/vars/Ubuntu-22.04.yml to newer version with updated versions where applicable.
Help/PR welcomed.

**Comment by juju4** [comment]
main HEAD has now an Ubuntu-24.04 pre-support with MISP 2.5 only.
There are still issues like misp-modules but it passes the ci. Not tested manually but please share feedback if you try. Thanks

**Comment by juju4** [comment]
I did a big manual review and 2.5/24.04 should be functional now.
Closing this.
