### ISSUE TITLE
Redis service is not set to enabled on centos7

### ISSUE THREAD

**Issue by lhirlimann** [juju4/ansible-MISP#5]
And thus the install doesn't like reboots.

**Comment by lhirlimann** [comment]
@juju4 I'll make a patch if you show me where that should lie.

**Comment by juju4** [comment]
redis is started here
https://github.com/juju4/ansible-MISP/blob/master/tasks/main.yml#L350
it was missing enabled and I added it (default on ubuntu, not on centos...)
