### ISSUE TITLE
pip install latest lief version is broken on ubuntu 18.04

### ISSUE THREAD

**Issue by TrinityIsStillMyName** [juju4/ansible-MISP#8]
Well, lief released new version 0.10.0 and 0.10.1 and current pip releases for python 2.7 are broken on ubuntu 18.04. See travis job log here https://travis-ci.org/juju4/ansible-MISP/jobs/617449500
```root@misp-vagrant:~# pip install lief==0.10.1
Collecting lief==0.10.1
  Using cached https://files.pythonhosted.org/packages/ee/b1/57241e2f5f7aac93d8d8d3ad46bf3f104a4f4ef171ca2eef38803f3868aa/lief-0.10.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-qm4nyK/lief/setup.py", line 306
        def format_version(version: str, fmt: str = fmt_dev, is_dev: bool = False):
                                  ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-qm4nyK/lief/
```

Using version 0.9.0 fixes the problem. MISP team still has lief 0.9.0 in their installation documentation, so i dont think its a problem to "downgrade" here

**Comment by juju4** [comment]
Thanks for notice.
using pip3 (https://github.com/juju4/ansible-MISP/commit/082fa751b81b3971d566aa85697bf3d8a8f51fe2) seems also to solve the problem and as we are approaching python2 official EOL, going that way

(other issues/misp-modules updates make travis failing - work in progress)
