### ISSUE TITLE
Ansible Galaxy role/collection resolves to version 1.10

### ISSUE THREAD

**Issue by galitz** [juju4/ansible-MISP#9]
Hi.. when installing from ansible galaxy, the latest version of ansible-MISP is 1.1.0, which fails for me on Ubuntu 20.04 and Centos 7.  When installing the role directly from GitHub it works correctly.

I have everything working fine, but others may be running into issues.

**Comment by juju4** [comment]
Thanks for notice.

I believe historically galaxy was getting new tag/release automatically but nowadays, need to push it.
I added in Feb the github action to do it automatically but I did my tagging before.
As a results, https://galaxy.ansible.com/juju4/misp still displayed last import one year ago.

just made a new minor tag 1.3.1 to force galaxy refresh, so should be good now.

alternatively, can use a galaxy requirements pointing to github and master branch as version like
```
- src: https://github.com/juju4/ansible-redhat-epel/
  version: master
  name: juju4.redhat_epel
```
